<?php foreach($this->biddingList as $bidding):?>
<div>
<h2>
<a href="<?php echo $this->url(array(
    'module' => 'bidding', 'controller' => 'index', 
    'action' => 'show', 'id' => $bidding->getId()
)); ?>"><?php echo $bidding->getTitle(); ?></a>
</h2>
<p><em> 
am <?php echo $bidding->getDate(); ?> 

<p><?php echo $bidding->getTeaser(); ?></p>
<p>
<a href="<?php echo $this->url(array(
    'module' => 'bidding', 'controller' => 'index', 
    'action' => 'show', 'id' => $bidding->getId()
)); ?>">weiter lesen</a>
</p>
</div>
<?php endforeach; ?>