<div>
<h2>
<a href="<?php echo $this->url(array(
 'module' => 'bidding', 'controller' => 'index', 
 'action' => 'show', 'id' => $this->bidding->getId()
)); ?>"><?php echo $this->bidding->getTitle(); ?></a>
</h2>
<p><em>
Geschrieben von 

am <?php echo $this->bidding->getDate(); ?> 

<p><?php echo $this->bidding->getText(); ?></p>
<p>
<a href="<?php echo $this->url(array(
 'module' => 'bidding', 'controller' => 'index', 
 'action' => 'index'
)); ?>">zurück</a>
</p>
</div>