<!DOCTYPE html>
<html lang="en">
<head>
	<title>Ausschreibungen</title>
    <meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="/css/styles.css" rel="stylesheet" type="text/css"/>

	<!--[if lte IE 7]>
	<link href="/css/yaml/core/iehacks.css" rel="stylesheet" type="text/css" />
	<![endif]-->

	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
<ul class="ym-skiplinks">
	<li><a class="ym-skip" href="#nav">Skip to navigation (Press Enter)</a></li>
	<li><a class="ym-skip" href="#main">Skip to main content (Press Enter)</a></li>
</ul>

<header>
	<div class="ym-wrapper">
		<div class="ym-wbox">
			<h1>Ausschreibungen</h1>
		</div>
	</div>
</header>

<nav id="nav">
	<div class="ym-wrapper">
		<div class="ym-hlist">
			<ul>
				<li class="active"><a href="/bidding">Ausschreibungen</a></li>
				<li><a href="/bidding/admin/create">Neue Ausschreibung</a></li>
				<!--<li><a href="#">Link</a></li>
				<li><a href="#">Link</a></li>
				<li><a href="#">Link</a></li>-->
			</ul>
			<form class="ym-searchform">
				<input class="ym-searchfield" type="search" placeholder="Search..." />
				<input class="ym-searchbutton" type="submit" value="Search" />
			</form>
		</div>
	</div>
</nav>

<div id="main">
	<div class="ym-wrapper">
		<div class="ym-wbox">
			<section class="ym-grid linearize-level-1">
				<article class="ym-g66 ym-gl content">
					<div class="ym-gbox-left ym-clearfix">
                        <?php echo $this->layout()->content; ?>
					</div>
				</article>
				<aside class="ym-g33 ym-gr">
					<div class="ym-gbox-right ym-clearfix">
						<h3>A Simple Sidebar </h3>
						<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices  posuere cubilia Curae; Cras ornare mattis nunc. Mauris venenatis, pede  sed aliquet vehicula, lectus tellus pulvinar neque, non cursus sem nisi vel augue.</p>
						<p class="box info">Mauris a lectus. Aliquam erat volutpat. Phasellus ultrices mi a sapien. Nunc rutrum egestas lorem. Duis ac sem sagittis elit tincidunt gravida. Mauris a lectus. Aliquam erat volutpat. Phasellus ultrices mi a sapien. Nunc rutrum egestas lorem. Duis ac sem sagittis elit tincidunt gravida.</p>
					</div>
				</aside>
			</section>
		</div>
	</div>
</div>

<footer>
	<div class="ym-wrapper">
		<div class="ym-wbox">
			<p>Â© Company 2012 &ndash; Layout based on <a href="http://www.yaml.de">YAML</a></p>
		</div>
	</div>
</footer>

<!-- full skip link functionality in webkit browsers -->
<script src="../yaml/core/js/yaml-focusfix.js"></script>
</body>
</html>